docfx.json, docs-ref-conceptual/Overview.md, docs-ref-conceptual/get-started.md
Through this pull request the metadata and version is being updated
=> Metadata and version update

docfx.json, docs-ref-conceptual/Overview.md, docs-ref-conceptual/get-started.md
Through this pull request the metadata and version references are being updated
=> Metadata and version update (#19)

.openpublishing.publish.config.json
Through this pull request the diff folder plugin is being removed.
=> Build configuration update

docs-ref-autogen/com.microsoft.store.partnercenter.BasePartnerComponent.yml, docs-ref-autogen/com.microsoft.store.partnercenter.IPartnerComponent.yml, docs-ref-autogen/com.microsoft.store.partnercenter.enumerators.ResourceCollectionEnumeratorContainer.yml, docs-ref-autogen/com.microsoft.store.partnercenter.genericoperations.IEntireEntityCollectionRetrievalOperations.yml, docs-ref-autogen/com.microsoft.store.partnercenter.invoices.IInvoice.yml, docs-ref-autogen/com.microsoft.store.partnercenter.invoices.IReconciliationLineItemCollection.yml, docs-ref-autogen/com.microsoft.store.partnercenter.invoices.InvoiceOperations.yml, docs-ref-autogen/com.microsoft.store.partnercenter.invoices.ReconciliationLineItemCollectionOperations.yml, docs-ref-autogen/com.microsoft.store.partnercenter.invoices.yml, docs-ref-autogen/com.microsoft.store.partnercenter.models.ApiFault.yml, docs-ref-autogen/com.microsoft.store.partnercenter.models.ResourceAttributes.yml, docs-ref-autogen/com.microsoft.store.partnercenter.models.auditing.OperationType.yml, docs-ref-autogen/com.microsoft.store.partnercenter.models.auditing.ResourceType.yml, docs-ref-autogen/com.microsoft.store.partnercenter.models.carts.CartLineItem.yml, docs-ref-autogen/com.microsoft.store.partnercenter.models.servicecosts.ServiceCostLineItem.yml, docs-ref-autogen/com.microsoft.store.partnercenter.models.servicecosts.ServiceCostsSummary.yml, docs-ref-autogen/com.microsoft.store.partnercenter.orders.IOrderActivationLinks.yml, docs-ref-autogen/com.microsoft.store.partnercenter.orders.yml, docs-ref-autogen/com.microsoft.store.partnercenter.subscriptions.ISubscription.yml, docs-ref-autogen/com.microsoft.store.partnercenter.subscriptions.ISubscriptionActivationLinks.yml, docs-ref-autogen/com.microsoft.store.partnercenter.subscriptions.SubscriptionActivationLinksOperations.yml, docs-ref-autogen/com.microsoft.store.partnercenter.subscriptions.SubscriptionCollectionOperations.yml, docs-ref-autogen/com.microsoft.store.partnercenter.subscriptions.SubscriptionOperations.yml, docs-ref-autogen/com.microsoft.store.partnercenter.subscriptions.yml, docs-ref-autogen/toc.yml, docs-ref-conceptual/Overview.md
Through this pull request the version is being updated
=> Updated the version

docfx.json, docs-ref-autogen/com.microsoft.store.partnercenter.models.ApiFault.yml, docs-ref-autogen/com.microsoft.store.partnercenter.models.invoices.BillingProvider.yml, docs-ref-autogen/com.microsoft.store.partnercenter.models.invoices.OneTimeInvoiceLineItem.yml, docs-ref-autogen/com.microsoft.store.partnercenter.models.orders.Order.yml, docs-ref-autogen/com.microsoft.store.partnercenter.models.users.CustomerUser.yml, docs-ref-autogen/com.microsoft.store.partnercenter.models.users.User.yml, docs-ref-conceptual/Overview.md
Through this pull request the date and version information is being updated
=> Minor update in preparation for the next release

docfx.json, docs-ref-autogen/com.microsoft.store.partnercenter.models.ApiFault.yml, docs-ref-autogen/com.microsoft.store.partnercenter.models.invoices.BillingProvider.yml, docs-ref-autogen/com.microsoft.store.partnercenter.models.invoices.OneTimeInvoiceLineItem.yml, docs-ref-autogen/com.microsoft.store.partnercenter.models.orders.Order.yml, docs-ref-autogen/com.microsoft.store.partnercenter.models.users.CustomerUser.yml, docs-ref-autogen/com.microsoft.store.partnercenter.models.users.User.yml, docs-ref-conceptual/Overview.md
* Minor update in preparation for the next release
* CI Update
=> Minor update in preparation for the next release (#27)

docs-ref-autogen/com.microsoft.store.partnercenter.IPartnerComponentString.yml, docs-ref-autogen/com.microsoft.store.partnercenter.customers.CustomerOperations.yml, docs-ref-autogen/com.microsoft.store.partnercenter.customers.ICustomer.yml, docs-ref-autogen/com.microsoft.store.partnercenter.customers.ICustomerCollection.yml, docs-ref-autogen/com.microsoft.store.partnercenter.customers.yml, docs-ref-autogen/com.microsoft.store.partnercenter.genericoperations.IEntityDeleteOperations.yml, docs-ref-autogen/com.microsoft.store.partnercenter.genericoperations.IEntityGetOperations.yml, docs-ref-autogen/com.microsoft.store.partnercenter.genericoperations.IEntityPatchOperations.yml, docs-ref-autogen/com.microsoft.store.partnercenter.models.ApiFault.yml, docs-ref-autogen/com.microsoft.store.partnercenter.models.carts.CartLineItem.yml, docs-ref-autogen/com.microsoft.store.partnercenter.models.carts.RenewsTo.yml, docs-ref-autogen/com.microsoft.store.partnercenter.models.carts.yml, docs-ref-autogen/com.microsoft.store.partnercenter.models.orders.OrderLineItem.yml, docs-ref-autogen/com.microsoft.store.partnercenter.models.orders.RenewsTo.yml, docs-ref-autogen/com.microsoft.store.partnercenter.models.orders.yml, docs-ref-autogen/com.microsoft.store.partnercenter.models.products.AvailabilityTerm.yml, docs-ref-autogen/com.microsoft.store.partnercenter.models.products.CancellationPolicy.yml, docs-ref-autogen/com.microsoft.store.partnercenter.models.products.CancellationRefundOption.yml, docs-ref-autogen/com.microsoft.store.partnercenter.models.products.ProductLinks.yml, docs-ref-autogen/com.microsoft.store.partnercenter.models.products.RenewalOption.yml, docs-ref-autogen/com.microsoft.store.partnercenter.models.products.yml, docs-ref-autogen/com.microsoft.store.partnercenter.models.subscriptions.Conversion.yml, docs-ref-autogen/com.microsoft.store.partnercenter.models.subscriptions.ConversionError.yml, docs-ref-autogen/com.microsoft.store.partnercenter.models.subscriptions.ConversionErrorCode.yml, docs-ref-autogen/com.microsoft.store.partnercenter.models.subscriptions.ConversionResult.yml, docs-ref-autogen/com.microsoft.store.partnercenter.models.subscriptions.Subscription.yml, docs-ref-autogen/toc.yml, docs-ref-conceptual/Overview.md
Through this pull request the version information is being updated
=> Updating the version information

docs-ref-autogen/com.microsoft.store.partnercenter.IPartnerComponentString.yml, docs-ref-autogen/com.microsoft.store.partnercenter.customers.CustomerOperations.yml, docs-ref-autogen/com.microsoft.store.partnercenter.customers.ICustomer.yml, docs-ref-autogen/com.microsoft.store.partnercenter.customers.ICustomerCollection.yml, docs-ref-autogen/com.microsoft.store.partnercenter.customers.yml, docs-ref-autogen/com.microsoft.store.partnercenter.genericoperations.IEntityDeleteOperations.yml, docs-ref-autogen/com.microsoft.store.partnercenter.genericoperations.IEntityGetOperations.yml, docs-ref-autogen/com.microsoft.store.partnercenter.genericoperations.IEntityPatchOperations.yml, docs-ref-autogen/com.microsoft.store.partnercenter.models.ApiFault.yml, docs-ref-autogen/com.microsoft.store.partnercenter.models.carts.CartLineItem.yml, docs-ref-autogen/com.microsoft.store.partnercenter.models.carts.RenewsTo.yml, docs-ref-autogen/com.microsoft.store.partnercenter.models.carts.yml, docs-ref-autogen/com.microsoft.store.partnercenter.models.orders.OrderLineItem.yml, docs-ref-autogen/com.microsoft.store.partnercenter.models.orders.RenewsTo.yml, docs-ref-autogen/com.microsoft.store.partnercenter.models.orders.yml, docs-ref-autogen/com.microsoft.store.partnercenter.models.products.AvailabilityTerm.yml, docs-ref-autogen/com.microsoft.store.partnercenter.models.products.CancellationPolicy.yml, docs-ref-autogen/com.microsoft.store.partnercenter.models.products.CancellationRefundOption.yml, docs-ref-autogen/com.microsoft.store.partnercenter.models.products.ProductLinks.yml, docs-ref-autogen/com.microsoft.store.partnercenter.models.products.RenewalOption.yml, docs-ref-autogen/com.microsoft.store.partnercenter.models.products.yml, docs-ref-autogen/com.microsoft.store.partnercenter.models.subscriptions.Conversion.yml, docs-ref-autogen/com.microsoft.store.partnercenter.models.subscriptions.ConversionError.yml, docs-ref-autogen/com.microsoft.store.partnercenter.models.subscriptions.ConversionErrorCode.yml, docs-ref-autogen/com.microsoft.store.partnercenter.models.subscriptions.ConversionResult.yml, docs-ref-autogen/com.microsoft.store.partnercenter.models.subscriptions.Subscription.yml, docs-ref-autogen/toc.yml, docs-ref-conceptual/Overview.md
Through this pull request updates are being made to reflect the latest release
=> Updating the version information (#30)

docs-ref-conceptual/breaking-changes.md, docs-ref-conceptual/get-started.md, docs-ref-conceptual/index.md, docs-ref-conceptual/release-notes.md, docs-ref-conceptual/toc.yml
Through this pull request the support materials are being updated. Also, information for breaking changes and release notes are being included.
=> Updating the supporting materials

docs-ref-conceptual/breaking-changes.md, docs-ref-conceptual/get-started.md, docs-ref-conceptual/index.md, docs-ref-conceptual/release-notes.md, docs-ref-conceptual/toc.yml
Through this pull request the supporting materials are being updated
=> Updating the supporting materials 

docs-ref-conceptual/breaking-changes.md, docs-ref-conceptual/get-started.md, docs-ref-conceptual/release-notes.md, docs-ref-conceptual/toc.yml
Through this pull request the naming for the SDK is being made consistent
=> Making the name for the SDK consistent

docs-ref-conceptual/overview.md
Through this pull request a link is being corrected.
=> Correcting a link

docfx.json, docs-ref-conceptual/breaking-changes.md, docs-ref-conceptual/get-started.md, docs-ref-conceptual/overview.md, docs-ref-conceptual/release-notes.md
Through this pull request updates are being made to reflect the latest release
=> Updates to reflect the latest release

docs-ref-mapping/reference.yml
Through this pull request the reference mapping is being updated
=> Updating the reference mapping

package.json
Through this pull request the package configuration is being updated
=> Updating the package configuration

.openpublishing.publish.config.json, docfx.json
=> Fix ms.service value

docfx.json, docs-ref-conceptual/get-started.md, docs-ref-conceptual/overview.md, docs-ref-conceptual/release-notes.md
Through this pull request updates are being made to prepare for the next release
=> Preparing for the next release

docs-ref-conceptual/get-started.md
Merging to master instead of live
=> Fix misspelled header + missing comma

.openpublishing.publish.config.json, .openpublishing.redirection.json, breadcrumb/toc.yml, docs-ref-autogen/com.microsoft.store.partnercenter.PartnerService.createPartnerOperations.yml, docs-ref-autogen/com.microsoft.store.partnercenter.customers.CustomerCollectionOperations.query.yml, docs-ref-autogen/com.microsoft.store.partnercenter.customers.ICustomerCollection.query.yml, docs-ref-autogen/com.microsoft.store.partnercenter.customerusers.CustomerUsersCollectionOperations.query.yml, docs-ref-autogen/com.microsoft.store.partnercenter.customerusers.ICustomerUserCollection.query.yml, docs-ref-autogen/com.microsoft.store.partnercenter.exception.PartnerResponseParseException.yml, docs-ref-autogen/com.microsoft.store.partnercenter.factory.IPartnerFactory.build.yml, docs-ref-autogen/com.microsoft.store.partnercenter.factory.IPartnerFactory.yml, docs-ref-autogen/com.microsoft.store.partnercenter.network.PartnerServiceRetryStrategy.PartnerServiceRetryStrategy.yml, docs-ref-autogen/com.microsoft.store.partnercenter.servicerequests.IServiceRequestCollection.query.yml, docs-ref-conceptual/index.md, partner-center-breadcrumb/toc.yml
[AB#294684](https://ceapex.visualstudio.com/Engineering/_workitems/edit/294684)
This Pull Request is for docfxv3 migration, after the Pull Request merged, the repository will be built with docfxv3 instead of docfxv2.
=> Update config to enable docfx v3

.openpublishing.publish.config.json, .openpublishing.redirection.json, breadcrumb/toc.yml, docs-ref-autogen/com.microsoft.store.partnercenter.PartnerService.createPartnerOperations.yml, docs-ref-autogen/com.microsoft.store.partnercenter.customers.CustomerCollectionOperations.query.yml, docs-ref-autogen/com.microsoft.store.partnercenter.customers.ICustomerCollection.query.yml, docs-ref-autogen/com.microsoft.store.partnercenter.customerusers.CustomerUsersCollectionOperations.query.yml, docs-ref-autogen/com.microsoft.store.partnercenter.customerusers.ICustomerUserCollection.query.yml, docs-ref-autogen/com.microsoft.store.partnercenter.exception.PartnerResponseParseException.yml, docs-ref-autogen/com.microsoft.store.partnercenter.factory.IPartnerFactory.build.yml, docs-ref-autogen/com.microsoft.store.partnercenter.factory.IPartnerFactory.yml, docs-ref-autogen/com.microsoft.store.partnercenter.network.PartnerServiceRetryStrategy.PartnerServiceRetryStrategy.yml, docs-ref-autogen/com.microsoft.store.partnercenter.servicerequests.IServiceRequestCollection.query.yml, docs-ref-conceptual/index.md, partner-center-breadcrumb/toc.yml
Update config to enable docfx v3
=> Update config to enable docfx v3 
